test build v2

diff --git a/.github/actions/run-build/action.yml b/.github/actions/run-build/action.yml
--- a/.github/actions/run-build/action.yml
+++ b/.github/actions/run-build/action.yml
@@ -42,5 +42,8 @@ runs:
           echo "!!! TAG is empty"
           exit 1
         fi
+        
+        echo "ERRORRR!!"
+        exit 1
 
-        sh ./scripts/manage.sh publish . ${{ inputs.repo }} ${{ inputs.tag }}
+#        sh ./scripts/manage.sh publish . ${{ inputs.repo }} ${{ inputs.tag }}
